root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/invoiceapi"
  cmd = "go build -gcflags='all=-N -l' -o ./tmp/invoiceapi ./cmd/invoiceapi"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "db"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "./tmp/invoiceapi"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "sql", "mod", "sum"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
